export const headerLinks =[
    //路由跳转
    {
        title:"发现音乐",
        link:"/discover"
    },
    {
        title:"我的音乐",
        link:"/mine"
    },
    {
        title:"朋友",
        link:"/friend"
    },
    //超链接跳转
    {
        title:"商城",
        link:"https://music.163.com/store/product"
    },
    {
        title:"音乐人",
        link:"https://music.163.com/st/musician"
    },
    {
        title:"下载客户端",
        link:"https://music.163.com/#/download"
    }
]

export const footerImages =[
    {
        link:"https://music.163.com/st/userbasic#/auth"
    },
    {
        link:"https://music.163.com/recruit"
    },
    {
        link:"https://music.163.com/web/reward"
    },
    {
        link:"https://music.163.com/uservideo#/plan"
    },
]

export const discoverMenu =[
    {
        title:"推荐",
        link:"/discover/recommend"
    },
    {
        title:"排行榜",
        link:"/discover/ranking"
    },
    {
        title:"歌单",
        link:"/discover/songs"
    },
    {
        title:"主播电台",
        link:"/discover/djradio"
    },
    {
        title:"歌手",
        link:"/discover/artist"
    },
    {
        title:"新碟上架",
        link:"/discover/album"
    }

]